<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book events</title>
</head>
<body onload="onPageLoad()">

<?php
/* This code dynamically generates a web page containing a form designed with the html required to display one
checkbox for each of the records currently held in the nmc_records database table has been provided for you in the
assessment section for the module on blackboard. The user can select one or more records that they are interested in
ordering by clicking the checkboxes.
Use the browser to look at the structure of the html generated by the php code. */

$url = "http://unn-izge1.newnumyspace.co.uk/KF5002/assessment/bookEventsFormInc.php";
$curl = curl_init($url);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
$result = curl_exec($curl);
curl_close($curl);
echo $result;
?>

<!-- Here you need to add Javascript or a link to a script (.js file) to process the form as required for the assignment -->
<script type="text/javascript">

    function onPageLoad() {
        document.getElementsByName('termsChkbx')[0].onclick = function () {
            modifyTermsAndConditionsStyle();
            modifySubmitButtonState();
        };

        document.getElementsByName('event[]').forEach(checkbox => {
            checkbox.onclick = function () {
                calculateTotal();
                modifySubmitButtonState();
            }
        });

        document.getElementsByName('deliveryType')[0].onclick = function () {
            calculateTotal();
        };

        document.getElementsByName('deliveryType')[1].onclick = function () {
            calculateTotal();
        };

        document.getElementsByName('surname')[0].addEventListener("input", function () {
            modifySubmitButtonState();
        });

        document.getElementsByName('forename')[0].addEventListener("input", function () {
            modifySubmitButtonState();
        });

        document.getElementsByName('companyName')[0].addEventListener("input", function () {
            modifySubmitButtonState();
        });

        document.getElementsByName ('customerType')[0].addEventListener('change', function () {
            disableNameFields ();
        });
    }

    //first time use
    calculateTotal();
    modifySubmitButtonState();


    function checkSurnameEmpty() {
        let isEmpty = true;
        if (document.getElementsByName('surname')[0].value === '') {
            isEmpty = false;
        }
        return isEmpty;
    }
    function checkForenameEmpty() {
        let isEmpty = true;
        if (document.getElementsByName('forename')[0].value === '') {
            isEmpty = false;
        }
        return isEmpty;
    }

    function checkCompanyName() {
        let isEmpty = true;
        if (document.getElementsByName('companyName')[0].value === '') {
            isEmpty = false;
        }
        return isEmpty;
    }

    function modifyTermsAndConditionsStyle() {
        const termsText = document.getElementById('termsText');
        if (document.getElementsByName('termsChkbx')[0].checked) {
            termsText.style.fontWeight = '400';
            termsText.style.color = 'black';
        } else {
            termsText.style.fontWeight = '700';
            termsText.style.color = 'red';
        }
    }

    function modifySubmitButtonState() {
        const submitButton = document.getElementsByName('submit')[0];
        if (checkListCheckboxState() && document.getElementsByName('termsChkbx')[0].checked && ((checkSurnameEmpty() && checkForenameEmpty()) || checkCompanyName())) {
            submitButton.disabled = false;
        } else {
            submitButton.disabled = true;
        }
    }

    function checkListCheckboxState() {
        let checked = false;
        document.getElementsByName('event[]').forEach(checkbox => {
            if (checkbox.checked) {
                checked = true;
            }
        });
        return checked;
    }

    /*
    Function to calculate total price.
     */
    function calculateTotal() {
        let totalPrice = 0;
        document.getElementsByName('event[]').forEach(checkbox => {
            if (checkbox.checked) {
                totalPrice = totalPrice + Number(checkbox.getAttribute('data-price'));
            }
        });
        document.getElementsByName('deliveryType').forEach(radio => {
            if (radio.checked) {
                totalPrice = totalPrice + Number(radio.getAttribute('data-price'));
            }
        });
        document.getElementsByName('total')[0].value = totalPrice;
    }

    function disableNameFields () {
        let customerName = document.getElementById('retCustDetails');
        let companyName = document.getElementById('tradeCustDetails');
        let customerType = document.getElementsByName('customerType')[0];
        if (customerType.value === "trd") {
            customerName.style.visibility="hidden";
            companyName.style.visibility="visible"
        } else {
            companyName.style.visibility="hidden";
            customerName.style.visibility="visible";
        }
    }

</script>
</body>
</html>